import {fileURLToPath} from 'node:url';
import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=fileURLToPath(new URL('..',import.meta.url));
const {communityAPI}=await import(root+'/server/community.mjs');
const courses=JSON.parse(fs.readFileSync(root+'/dist/academy-courses.json'));
const lessons={'python-dsa':JSON.parse(fs.readFileSync(root+'/dist/course-python.json')).map(l=>({id:l.id,problemCount:l.problems.length})),'java-basics':JSON.parse(fs.readFileSync(root+'/dist/curriculum.json')).map(l=>({id:l.id,problemCount:1}))};for(const c of courses)lessons[c.id]=c.lessons.map(l=>({id:l.id,problemCount:1}));
const db=new DatabaseSync(':memory:');for(const f of fs.readdirSync(root+'/drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync(root+'/drizzle/'+f,'utf8'));
let hook=null;function statement(sql,args=[]){const st=db.prepare(sql);return{bind(...a){return statement(sql,a)},async first(){if(hook&&hook.re.test(sql)){const h=hook;hook=null;h.change();}return st.get(...args)||null},async all(){return{results:st.all(...args)}},async run(){return st.run(...args)}}}const env={DB:{prepare:statement,async batch(qs){return Promise.all(qs.map(q=>q.run()))}}};
const tokens={};for(const user of ['A','B','C'])tokens[user]=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('codetrail-community-v1|'+user)))].map(x=>x.toString(16).padStart(2,'0')).join('');
async function call(u,body=null,params='course=python-dsa&room=r&panes=1',origin='https://test.local') {const h={};if(u)h['oai-authenticated-user-id']=u;if(body){h['content-type']='application/json';h.origin=origin;}const r=await communityAPI(new Request('https://test.local/api/community?'+params,{method:body?'POST':'GET',headers:h,...body?{body:JSON.stringify({self:tokens[u],courseId:'python-dsa',roomId:'r',...body})}:{}}),env,courses,lessons);return{status:r.status,...await r.json()};}
function fixture(){hook=null;for(const t of ['study_room_focus','study_buffers','study_buffer_permissions','community_reports','community_messages','community_blocks','study_members','study_rooms','study_connections','course_enrollments','community_profiles'])db.exec('DELETE FROM '+t);for(const u of ['A','B','C']){db.prepare('INSERT INTO community_profiles VALUES (?,?,?)').run(u,'public-'+u,'User '+u);for(const course of Object.keys(lessons))db.prepare('INSERT INTO course_enrollments VALUES (?,?,?,?,?)').run(course+'|'+u,course,u,1,1);}db.exec("INSERT INTO study_rooms VALUES ('r','python-dsa','A','Room','python','ORIGINAL OWNER CODE',3,1,0); INSERT INTO study_members VALUES ('r|B','r','B','editor'); INSERT INTO study_buffers VALUES ('r|B','r','B','ORIGINAL MEMBER CODE',2,1,1)");}
let checks=0;function check(label,actual,expect){assert.deepEqual(actual,expect,label);checks++;console.log('PASS '+label);}
const valid={action:'setFocus',lessonId:'py03',problemIndex:1};fixture();check('Existing room initially has null focus',(await call('A')).room.focus,null);check('Anonymous cannot read',(await call(null)).status,401);check('Anonymous cannot write',(await call(null,valid)).status,401);check('Host sets focus',(await call('A',valid)).status,200);check('Viewer reads shared focus',(await call('B')).room.focus.lessonId,'py03');check('Problem index persists',(await call('B')).room.focus.problemIndex,1);check('Owner buffer unchanged',db.prepare('SELECT code FROM study_rooms').get().code,'ORIGINAL OWNER CODE');check('Member buffer unchanged',db.prepare('SELECT code FROM study_buffers').get().code,'ORIGINAL MEMBER CODE');check('Editor cannot set focus',(await call('B',{...valid,lessonId:'py04'})).status,403);check('Outsider cannot set focus',(await call('C',valid)).status,403);check('Outsider cannot read',(await call('C')).status,404);check('Wrong course lesson rejected',(await call('A',{...valid,lessonId:'variables'})).status,400);check('Unknown lesson rejected',(await call('A',{...valid,lessonId:'<script>'})).status,400);for(const v of [-1,2,0.5,'0',null])check('Invalid index '+v,(await call('A',{...valid,problemIndex:v})).status,400);check('Cross-course room rejected',(await call('A',{action:'setFocus',courseId:'java-basics',lessonId:'variables',problemIndex:0})).status,403);check('Cross-origin write denied',(await call('A',valid,undefined,'https://evil.local')).status,403);check('Wrong self denied',(await call('A',{...valid,self:tokens.B})).status,409);check('Repeated update succeeds',(await call('A',{...valid,lessonId:'py48',problemIndex:0})).status,200);check('Latest update persists',(await call('B')).room.focus.lessonId,'py48');
for(const [label,sql] of [['closed',"UPDATE study_rooms SET closed=1"],['unenrolled',"DELETE FROM course_enrollments WHERE user_id='A' AND course_id='python-dsa'"],['owner changed',"UPDATE study_rooms SET owner_id='C'"],['course changed',"UPDATE study_rooms SET course_id='java-basics'"]]){fixture();hook={re:/INSERT INTO study_room_focus/,change:()=>db.exec(sql)};check('Write-time race '+label,(await call('A',valid)).status,403);check('No focus inserted '+label,db.prepare('SELECT count(*) AS n FROM study_room_focus').get().n,0);}
for(const [course,rows] of Object.entries(lessons)){fixture();db.prepare('UPDATE study_rooms SET course_id=?').run(course);for(const lesson of rows){for(let i=0;i<lesson.problemCount;i++){const r=await call('A',{action:'setFocus',courseId:course,lessonId:lesson.id,problemIndex:i});assert.equal(r.status,200,course+' '+lesson.id+' '+i);}}checks++;console.log('PASS every valid focus '+course);}
console.log('All '+checks+' focus checks passed; every course/lesson/challenge accepted.');
