import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
import vm from 'node:vm';
const root=path.resolve(fileURLToPath(new URL('..',import.meta.url)));
const {communityAPI}=await import(pathToFileURL(path.join(root,'server/community.mjs')));
const db=new DatabaseSync(':memory:');
for(const file of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync(path.join(root,'drizzle',file),'utf8'));
let hook=null;
function statement(sql,args=[]){const stmt=db.prepare(sql);function before(){if(hook&&hook.re.test(sql)){const h=hook;hook=null;h.change();}}return{bind(...a){return statement(sql,a)},async first(){before();return stmt.get(...args)||null},async all(){before();return{results:stmt.all(...args)}},async run(){before();if(/\bRETURNING\b/i.test(sql))return{results:stmt.all(...args),meta:{changes:db.prepare('SELECT changes() n').get().n}};const r=stmt.run(...args);return{results:[],meta:{changes:r.changes,last_row_id:r.lastInsertRowid}}}}}
const env={DB:{prepare:statement,async batch(qs){db.exec('BEGIN');try{const out=[];for(const q of qs)out.push(await q.run());db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}}};
const failures=[];let checks=0;
function check(name,got,want){checks++;const pass=Array.isArray(want)?want.includes(got):got===want;if(!pass)failures.push({name,got,want});console.log(`${pass?'PASS':'FAIL'} ${name}${pass?'':': '+JSON.stringify({got,want})}`)}
async function identity(u){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('codetrail-community-v1|'+u)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
const tokens={};for(const u of ['AliceSecretAuth','BobSecretAuth','CarolSecretAuth','A','B','C'])tokens[u]=await identity(u);
const {bufferAPI}=await import(pathToFileURL(path.join(root,'server/buffers.mjs')));
tokens.D=await identity('D');
async function api(u,body,params='course=python-dsa',origin=true){const h={};if(u)h['oai-authenticated-user-id']=u;if(body){h['content-type']='application/json';if(origin)h.origin='https://local.test'}const r=await communityAPI(new Request('https://local.test/api/community?'+params,{method:body?'POST':'GET',headers:h,...(body?{body:JSON.stringify({self:tokens[u],courseId:'python-dsa',...body})}:{})}),env,[]);return {status:r.status,...await r.json()}}
async function buf(u,owner=u,body=null,origin=true){const h={};if(u)h['oai-authenticated-user-id']=u;if(body){h['content-type']='application/json';if(origin)h.origin='https://local.test'}const r=await bufferAPI(new Request('https://local.test/api/buffer?course=python-dsa&room=room&learner=public-'+owner,{method:body?'POST':'GET',headers:h,...(body?{body:JSON.stringify({self:tokens[u],courseId:'python-dsa',roomId:'room',learnerId:'public-'+owner,...body})}:{})}),env);return{status:r.status,...await r.json()}}
function fixture(){hook=null;for(const t of ['study_buffer_permissions','study_buffers','community_blocks','community_messages','community_reports','study_members','study_connections','study_rooms','course_enrollments','community_profiles'])db.exec('DELETE FROM '+t);for(const u of ['A','B','C','D']){db.prepare('INSERT INTO community_profiles VALUES (?,?,?)').run(u,'public-'+u,'Learner '+u);db.prepare('INSERT INTO course_enrollments VALUES (?,?,?,?,?)').run('python-dsa|'+u,'python-dsa',u,1,1)}db.exec("INSERT INTO study_connections VALUES ('connAB','pairAB','python-dsa','A','B','accepted',1),('connAC','pairAC','python-dsa','A','C','accepted',1);INSERT INTO study_rooms VALUES ('room','python-dsa','A','Room title','python','OWNER_CODE',1,1,0);INSERT INTO study_members VALUES ('room|B','room','B','viewer'),('room|C','room','C','viewer')")}
function bufferFixture(){fixture();db.exec("INSERT INTO study_buffers VALUES ('room|B','room','B','B_PRIVATE_CODE',1,1,1);INSERT INTO study_buffer_permissions VALUES ('room|B|C','room','B','C')")}
fixture();check('Anonymous buffer denied',(await buf(null,'A')).status,401);check('Outsider denied owner buffer',(await buf('D','A')).status,403);check('Outsider denied member buffer',(await buf('D','B')).status,403);
const own=await buf('B');check('Member owns blank buffer',own.code,'');check('Own buffer writable',own.canEdit,true);check('Own buffer private',own.shared,false);check('Peer cannot view blank private buffer',(await buf('C','B')).status,403);check('Room owner cannot view member private buffer',(await buf('A','B')).status,403);
check('Member can save own buffer',(await buf('B','B',{action:'save',code:'B_PRIVATE_CODE',revision:0})).status,200);check('Member private save stays private',(await buf('B')).shared,false);check('Another member cannot share B buffer',(await buf('C','B',{action:'share',shared:true})).status,403);check('Owner can share own buffer',(await buf('B','B',{action:'share',shared:true})).status,200);check('Peer can now read',(await buf('C','B')).code,'B_PRIVATE_CODE');check('Peer initially read-only',(await buf('C','B')).canEdit,false);check('Room owner cannot edit peer by default',(await buf('A','B')).canEdit,false);check('Read-only peer cannot save',(await buf('C','B',{action:'save',code:'bad',revision:1})).status,403);check('Own grant succeeds',(await buf('B','B',{action:'grant',granteeId:'public-C',allow:true})).status,200);check('Peer can edit after grant',(await buf('C','B')).canEdit,true);check('Peer save after grant succeeds',(await buf('C','B',{action:'save',code:'B_EDITED_BY_C',revision:1})).status,200);check('CAS stale revision rejected',(await buf('B','B',{action:'save',code:'stale',revision:1})).status,409);check('Outsider grant denied',(await buf('B','B',{action:'grant',granteeId:'public-D',allow:true})).status,403);check('Peer cannot grant someone else',(await buf('C','B',{action:'grant',granteeId:'public-A',allow:true})).status,403);
check('Owner hide succeeds',(await buf('B','B',{action:'share',shared:false})).status,200);check('Peer cannot read hidden',(await buf('C','B')).status,403);check('Hide deletes old grants',db.prepare('SELECT count(*) n FROM study_buffer_permissions').get().n,0);await buf('B','B',{action:'share',shared:true});check('Reshare does not restore grant',(await buf('C','B')).canEdit,false);
fixture();await buf('B','B',{action:'share',shared:true});check('Share empty editor then first save succeeds',(await buf('B','B',{action:'save',code:'saved after sharing',revision:0})).status,200);
bufferFixture();await api('A',{action:'role',roomId:'room',learnerId:'public-C',role:'remove'});check('Removed grantee cannot read',(await buf('C','B')).status,403);await api('A',{action:'invite',roomId:'room',learnerId:'public-C'});check('Reinvite does not revive old edit grant',(await buf('C','B')).canEdit,false);
bufferFixture();await api('B',{action:'block',learnerId:'public-C'});check('Blocked co-member cannot read',(await buf('C','B')).status,403);await api('B',{action:'unblock',learnerId:'public-C'});check('Unblock does not revive old edit grant',(await buf('C','B')).canEdit,false);
bufferFixture();await api('A',{action:'role',roomId:'room',learnerId:'public-B',role:'remove'});await api('A',{action:'invite',roomId:'room',learnerId:'public-B'});check('Reinvited buffer owner resets sharing',(await buf('B','B')).shared,false);
bufferFixture();await api('C',{action:'leave'});await api('C',{action:'join',handle:'Learner C',discoverable:true});await api('A',{action:'connect',learnerId:'public-C'});db.exec("UPDATE study_connections SET status='accepted' WHERE target='C'");await api('A',{action:'invite',roomId:'room',learnerId:'public-C'});check('Leave/rejoin does not revive old edit grant',(await buf('C','B')).canEdit,false);
for(const [label,sql]of [['actor removed',"DELETE FROM study_members WHERE user_id='C'"],['target removed',"DELETE FROM study_members WHERE user_id='B'"],['room owner unenrolled',"DELETE FROM course_enrollments WHERE user_id='A'"],['actor unenrolled',"DELETE FROM course_enrollments WHERE user_id='C'"],['target unenrolled',"DELETE FROM course_enrollments WHERE user_id='B'"],['actor-target blocked',"INSERT INTO community_blocks VALUES('B|C','B','C')"],['actor-owner blocked',"INSERT INTO community_blocks VALUES('A|C','A','C')"],['target-owner blocked',"INSERT INTO community_blocks VALUES('A|B','A','B')"],['target hidden',"UPDATE study_buffers SET shared=0 WHERE owner_id='B'"],['grant revoked',"DELETE FROM study_buffer_permissions"],['room closed',"UPDATE study_rooms SET closed=1"]]){bufferFixture();hook={re:/UPDATE study_buffers SET code/,change:()=>db.exec(sql)};const result=await buf('C','B',{action:'save',code:'RACE_BAD',revision:1});check('Write race '+label+' hook',hook===null,true);check('Write race '+label,result.status,[403,404,409]);check('Write race '+label+' preserved data',db.prepare("SELECT code FROM study_buffers WHERE owner_id='B'").get().code,'B_PRIVATE_CODE')}
fixture();await buf('B','B',{action:'share',shared:true});await buf('B','B',{action:'grant',granteeId:'public-C',allow:true});check('Authorized peer can first-save shared empty editor',(await buf('C','B',{action:'save',code:'peer first save',revision:0})).status,200);check('Peer first-save preserves sharing',(await buf('B','B')).shared,true);
fixture();check('Room owner buffer must use one permission model',(await buf('A','A',{action:'grant',granteeId:'public-B',allow:true})).status,[400,403]);
fixture();const paneState=await api('B',null,'course=python-dsa&room=room&panes=1');check('Panes community response excludes owner code','code' in paneState.room,false);check('Legacy community keeps owner code',(await api('B',null,'course=python-dsa&room=room')).room.code,'OWNER_CODE');check('Legacy viewer owner buffer read-only',(await buf('B','A')).canEdit,false);await api('A',{action:'role',roomId:'room',learnerId:'public-B',role:'editor'});check('Legacy editor grants owner buffer editing',(await buf('B','A')).canEdit,true);check('Owner buffer CAS save works',(await buf('B','A',{action:'save',code:'changed owner code',revision:1})).status,200);await api('A',{action:'role',roomId:'room',learnerId:'public-B',role:'viewer'});check('Legacy revoke locks owner buffer',(await buf('B','A')).canEdit,false);
for(const [label,sql]of [['grant owner removed',"DELETE FROM study_members WHERE user_id='B'"],['grantee removed',"DELETE FROM study_members WHERE user_id='C'"],['room owner unenrolled',"DELETE FROM course_enrollments WHERE user_id='A'"],['grant owner unenrolled',"DELETE FROM course_enrollments WHERE user_id='B'"],['grantee unenrolled',"DELETE FROM course_enrollments WHERE user_id='C'"],['grant owner-grantee blocked',"INSERT INTO community_blocks VALUES('B|C','B','C')"],['grantee-room owner blocked',"INSERT INTO community_blocks VALUES('A|C','A','C')"],['grant owner-room owner blocked',"INSERT INTO community_blocks VALUES('A|B','A','B')"],['buffer hidden',"UPDATE study_buffers SET shared=0 WHERE owner_id='B'"],['room closed',"UPDATE study_rooms SET closed=1"]]){bufferFixture();db.exec('DELETE FROM study_buffer_permissions');hook={re:/INSERT INTO study_buffer_permissions/,change:()=>db.exec(sql)};const result=await buf('B','B',{action:'grant',granteeId:'public-C',allow:true});check('Grant race '+label+' hook',hook===null,true);check('Grant race '+label,result.status,[403,404,409]);check('Grant race '+label+' creates no permission',db.prepare('SELECT COUNT(*) n FROM study_buffer_permissions').get().n,0)}
for(const [label,sql]of [['actor removed',"DELETE FROM study_members WHERE user_id='C'"],['target removed',"DELETE FROM study_members WHERE user_id='B'"],['room owner unenrolled',"DELETE FROM course_enrollments WHERE user_id='A'"],['actor unenrolled',"DELETE FROM course_enrollments WHERE user_id='C'"],['target unenrolled',"DELETE FROM course_enrollments WHERE user_id='B'"],['actor-target blocked',"INSERT INTO community_blocks VALUES('B|C','B','C')"],['actor-owner blocked',"INSERT INTO community_blocks VALUES('A|C','A','C')"],['target-owner blocked',"INSERT INTO community_blocks VALUES('A|B','A','B')"],['target hidden',"UPDATE study_buffers SET shared=0 WHERE owner_id='B'"],['room closed',"UPDATE study_rooms SET closed=1"]]){bufferFixture();db.exec(sql);const result=await buf('C','B');check('Read denied '+label,result.status,[403,404]);check('No code leaks on denied '+label,JSON.stringify(result).includes('B_PRIVATE_CODE'),false)}
fixture();check('Buffer CSRF rejects no origin',(await buf('B','B',{action:'save',code:'BAD',revision:0},false)).status,403);check('Buffer rejects switched identity',(await buf('B','B',{action:'save',code:'BAD',revision:0,self:tokens.C})).status,409);check('Buffer rejects negative revision',(await buf('B','B',{action:'save',code:'BAD',revision:-1})).status,400);check('Buffer rejects oversized code',(await buf('B','B',{action:'save',code:'x'.repeat(16001),revision:0})).status,400);check('Buffer response hides raw IDs',JSON.stringify(await buf('B','B')).includes('owner_id'),false);
let output='';const prev=process.cwd();process.chdir(root);const shim={readdirSync:fs.readdirSync,readFileSync:fs.readFileSync,existsSync:fs.existsSync,mkdirSync(){},writeFileSync(p,body){output=body}};new Function('fs',fs.readFileSync('build.mjs','utf8').replace("import fs from 'node:fs';",''))(shim);process.chdir(prev);const worker=new Function(output.replace('export default {','return {'))();
check('Bundled anonymous buffer route denied',(await worker.fetch(new Request('https://local.test/api/buffer?course=python-dsa&room=room'),env)).status,401);const bundled=await worker.fetch(new Request('https://local.test/api/buffer?course=python-dsa&room=room',{headers:{'oai-authenticated-user-id':'B'}}),env);check('Bundled signed-in buffer route works',bundled.status,200);check('Bundled signed-in own editor default',(await bundled.json()).own,true);
console.log('\n'+JSON.stringify({checks,passed:checks-failures.length,failures},null,2));process.exitCode=failures.length?1:0;
