const academyResponse=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'private, no-store','Vary':'Cookie','X-Content-Type-Options':'nosniff'}});
const academyBlank=()=>({quizPassed:[],codeDrafts:{},tasks:{},ratings:{},lastLesson:null,memory:{enabled:false,notes:'',turns:[],epoch:0}});
export function academyCatalog(courses){const lessons=new Map(),tasks=new Map();for(const c of courses){for(const l of c.lessons){lessons.set(l.id,{course:c,lesson:l});tasks.set(l.task.id,{...l.task,courseId:c.id,lessonId:l.id,capstone:false});}tasks.set(c.id+'-capstone',{id:c.id+'-capstone',...c.capstone,courseId:c.id,capstone:true});}return{lessons,tasks};}
export function academySummary(state,courses){const cat=academyCatalog(courses),passed=new Set(state.quizPassed),taskIds=Object.keys(state.tasks).filter(k=>cat.tasks.has(k)),completed=courses.filter(c=>c.lessons.every(l=>passed.has(l.id)&&state.tasks[l.task.id])&&state.tasks[c.id+'-capstone']);const quizCount=[...passed].filter(k=>cat.lessons.has(k)).length;const xp=quizCount*15+taskIds.reduce((n,k)=>n+(cat.tasks.get(k).capstone?75:25),0)+completed.length*100;return{points:xp,credits:completed.reduce((n,c)=>n+c.credits,0),coursesCompleted:completed.map(c=>c.id),quizzesPassed:quizCount,tasksCompleted:taskIds.length,level:xp>=5000?'Orbit':xp>=2500?'Pioneer':xp>=1000?'Builder':xp>=250?'Explorer':'Launch',nextLevelAt:[250,1000,2500,5000].find(n=>n>xp)||null};}
export function academyAction(state,input,courses){const out=structuredClone(state),cat=academyCatalog(courses),now=Date.now();const error=(message,status=400)=>({error:message,status});switch(input.action){case'visit':{if(!cat.lessons.has(input.lessonId))return error('Unknown lesson');out.lastLesson=input.lessonId;break;}
case'quiz':{const l=cat.lessons.get(input.lessonId)?.lesson;if(!l||!Array.isArray(input.answers)||input.answers.length!==l.quiz.length||input.answers.some((a,i)=>!Number.isInteger(a)||a<0||a>=l.quiz[i].choices.length))return error('Answer every checkpoint question.');const results=l.quiz.map((q,i)=>({correct:q.answer===input.answers[i],explanation:q.explanation}));if(results.every(r=>r.correct))out.quizPassed=[...new Set([...out.quizPassed,l.id])];return{state:out,results,passed:results.every(r=>r.correct)};}
case'task':{const task=cat.tasks.get(input.taskId);if(!task)return error('Unknown task');if(typeof input.evidence!=='string'||input.evidence.trim().length<120||input.evidence.length>12000||!Array.isArray(input.checks)||input.checks.length!==task.rubric.length||!input.checks.every(v=>v===true))return error('Submit at least 120 characters of your work and confirm every rubric item.');out.tasks[task.id]={evidence:input.evidence.trim(),completedAt:out.tasks[task.id]?.completedAt||now,updatedAt:now};break;}
case'codeDraft':{if(!cat.lessons.has(input.lessonId)||typeof input.code!=='string'||input.code.length>16000)return error('Unknown lesson or code exceeds 16,000 characters.');out.codeDrafts={...(out.codeDrafts||{}),[input.lessonId]:input.code};break;}
case'rate':{if(!courses.some(c=>c.id===input.courseId)||!Number.isInteger(input.rating)||input.rating<1||input.rating>5)return error('Choose a rating from one to five.');out.ratings[input.courseId]=input.rating;break;}
case'memorySettings':{if(typeof input.enabled!=='boolean'||typeof input.notes!=='string'||input.notes.length>2000)return error('Invalid memory preferences');out.memory.enabled=input.enabled;out.memory.notes=input.notes;break;}
case'memoryAppend':{if(!out.memory.enabled)return error('Account memory is disabled.',409);if(input.epoch!==out.memory.epoch)return error('Memory was cleared while this answer was running. The old conversation was not restored.',409);if(typeof input.id!=='string'||!/^[-\w]{1,80}$/.test(input.id)||typeof input.user!=='string'||input.user.length>3000||typeof input.assistant!=='string'||input.assistant.length>12000||typeof input.context!=='string'||input.context.length>160)return error('Conversation exceeds memory limits');if(!out.memory.turns.some(t=>t.id===input.id)){out.memory.turns.push({id:input.id,user:input.user,assistant:input.assistant,context:input.context,at:now});out.memory.turns=out.memory.turns.slice(-20);}break;}
case'memoryClear':{out.memory.turns=[];out.memory.epoch++;break;}
default:return error('Unknown action');}return{state:out};}
export async function academyAPI(request,env,courses){const user=request.headers.get('oai-authenticated-user-id');if(!user)return academyResponse({error:'Sign in to use your account learning records.'},401);const get=async()=>{const row=await env.DB.prepare('SELECT state_json,revision FROM academy_state WHERE user_id=?').bind(user).first();return row?{state:JSON.parse(row.state_json),revision:row.revision}:{state:academyBlank(),revision:0};};try{if(request.method==='GET'){const current=await get();return academyResponse({account:user,...current,summary:academySummary(current.state,courses)});}if(request.method!=='POST')return academyResponse({error:'Method not allowed'},405);if(request.headers.get('origin')!==new URL(request.url).origin)return academyResponse({error:'Request origin rejected'},403);if(!request.headers.get('content-type')?.includes('application/json'))return academyResponse({error:'Expected JSON'},415);const reader=request.body?.getReader();if(!reader)return academyResponse({error:'Missing data'},400);let size=0,parts=[];while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>100000){await reader.cancel();return academyResponse({error:'Request too large'},413);}parts.push(value);}const bytes=new Uint8Array(size);let n=0;for(const p of parts){bytes.set(p,n);n+=p.length;}let input;try{input=JSON.parse(new TextDecoder().decode(bytes));}catch{return academyResponse({error:'Invalid JSON'},400);}if(!input||typeof input!=='object'||input.account!==user)return academyResponse({account:user,error:'The signed-in account changed. Reload before continuing.'},409);
for(let tries=0;tries<5;tries++){const current=await get(),result=academyAction(current.state,input,courses);if(result.error)return academyResponse({error:result.error},result.status);const payload=JSON.stringify(result.state),now=Date.now();if(payload.length>1800000)return academyResponse({error:"Your learning records are too large. Shorten older task submissions or code drafts before saving."},413);const saved=current.revision===0?await env.DB.prepare('INSERT INTO academy_state (user_id,state_json,revision,updated_at) VALUES (?,?,1,?) ON CONFLICT(user_id) DO NOTHING RETURNING revision').bind(user,payload,now).first():await env.DB.prepare('UPDATE academy_state SET state_json=?,revision=revision+1,updated_at=? WHERE user_id=? AND revision=? RETURNING revision').bind(payload,now,user,current.revision).first();if(saved)return academyResponse({account:user,state:result.state,revision:saved.revision,summary:academySummary(result.state,courses),...(result.results?{results:result.results,passed:result.passed}:{})});}return academyResponse({error:'Your account is busy updating. Retry in a moment.'},409);}catch{return academyResponse({error:'Learning records are temporarily unavailable. Keep your work and retry.'},503);}}
